version: 1
disable_existing_loggers: false

root:
    level: WARNING
    handlers: [console]

loggers:
    geometric_algorithms:
        level: WARNING
        handlers: [console, logfile]
        propagate: no

    geometric_algorithms.Finder:
        level: WARNING
        handlers: [console, logfile]
        propagate: yes
    geometric_algorithms.P1:
        level: WARNING
        handlers: [console, logfile]
        propagate: no
    geometric_algorithms.P2:
        level: WARNING
        handlers: [console, logfile]
        propagate: yes
    geometric_algorithms.P3:
        level: WARNING
        handlers: [console, logfile]
        propagate: yes
    geometric_algorithms.S1:
        level: WARNING
        handlers: [console, logfile]
        propagate: yes
    geometric_algorithms.S2:
        level: WARNING
        handlers: [console, logfile]
        propagate: yes
    geometric_algorithms.W1:
        level: WARNING
        handlers: [console, logfile]
        propagate: yes
    geometric_algorithms.W2:
        level: WARNING
        handlers: [console, logfile]
        propagate: yes

    geomeric_algorithms.geo_algorithms.parse_scores():
        level: WARNING
        handlers: [console]
        propagate: no
    geometric_algorithms.geo_algorithms.process_settings():
        level: WARNING
        handlers: [console]
        propagate: no
    geometric_algorithms.geo_algorithms.pre_process():
        level: WARNING
        handlers: [console]
        propagate: no

    NoteSegment:
        level: WARNING
        handlers: [console, logfile]
        propagate: no
    VectorCreation:
        level: WARNING
        handlers: [console]
        propagate: no

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

    logfile:
        class: logging.FileHandler
        level: DEBUG
        formatter: simple
        filename: debug.log

formatters:
    simple:
        class: logging.Formatter
        format: "%(asctime)s - %(name)s - %(levelname)s - %(funcName)s \n %(message)s \n"

