openapi: 3.0.1
info:
  description: "Content-Based Music Retrieval"
  version: "1.0.0"
  title: "PatternFinder"
  contact:
    email: "david.garfinkle@mail.mcgill.ca"
servers:
  - "url": "https://132.206.14.238:{port}/{basePath}"
    "description": "Development server"
    "variables":
        port:
          default: "8080"
        basePath:
          default: "api/v1"
  - "url": "https://patternfinder.elvisproject.ca"
    "description": "Production server"
paths:
  /search:
    get:
      operationId: "search"
      parameters:
        - name: "inputType"
          in: "query"
          description: "Indicates the music encoding language of the query string"
          schema:
            type: "string"
        - name: "query"
          in: "query"
          description: "A music query string"
          schema:
            type: "string"
      responses:
        200:
          description: "The server successfully completed a search for the music query and is returning the result(s)" 
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/occurrence"
  /piece/{pieceName}:
    get:
      operationId: "getPiece"
      parameters:
        - name: "pieceName"
          in: "path"
          description: "Name of the piece to retrieve"
          schema:
            type: "string"
        - name: "noteIndices"
          in: "query"
          description: "Indices of notes relative to the entire score which define the boundaries of this excerpt"
          schema:
            type: "array"
            items: 
              type: "integer"
      responses:
        200:
          description: "The server successfully completed a search for this mass and is returning the music-encoded document or an excerpt thereof"
components:
  schemas:
    occurrence:
      type: "object"
      properties:
        pieceName:
          type: "string"
        targetNotes:
          type: "array"
          items: 
            type: "integer"
        diatonicOcc:
          type: "boolean"
        transposition:
          type: "integer"

