openapi: 3.0.1
info: 
  description: "Content-Based Music Retrieval"
  version: "1.0.0"
  title: "PatternFinder"
  contact:
    email: "david.garfinkle@mail.mcgill.ca"
servers:
  - "url": "https://132.206.14.238:8000" 
    "description": "Development server"
paths:
  /search:
    get:
      operationId: "search"
      parameters:
        - name: "inputType"
          in: "query"
          description: "Indicates the music encoding language of the query string"
          schema:
            type: "string"
        - name: "musicQuery"
          in: "query"
          description: "A music query string"
          schema:
            type: "string"
      responses:
        200:
          description: "The server successfully completed a search for the music query and is returning the result(s)" 
components:
  schemas:
    occurrence:
      type: "object"
      properties:
        mass:
          type: "string"
        targetNotes:
          type: "array"
          items: 
            type: "integer"
        diatonicOcc:
          type: "boolean"
        transposition:
          type: "integer"

