version: 1
disable_existing_loggers: false

root:
    level: WARNING
    handlers: [console]

loggers:
    geometric_helsinki:
        level: WARNING
        handlers: [console, logfile]
        propagate: no

    geometric_helsinki.finder:
        level: WARNING
        filters: [finder_function]
        propagate: yes

    geometric_helsinki.algorithms:
        level: WARNING
        propagate: yes

    geometric_helsinki.P1:
        level: WARNING
        propagate: yes
    geometric_helsinki.algorithms.P2:
        level: WARNING
        propagate: yes
    geometric_helsinki.P3:
        level: WARNING
        propagate: yes
    geometric_helsinki.S1:
        level: WARNING
        propagate: yes
    geometric_helsinki.S2:
        level: WARNING
        propagate: yes
    geometric_helsinki.W1:
        level: WARNING
        propagate: yes
    geometric_helsinki.W2:
        level: WARNING
        propagate: yes

    NoteSegment:
        level: WARNING
        handlers: [console, logfile]
        propagate: no
    VectorCreation:
        level: WARNING
        handlers: [console]
        propagate: no

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

    logfile:
        class: logging.FileHandler
        level: DEBUG
        formatter: simple
        filename: debug.log

filters:
    finder_function:
        name: geometric_helsinki.finder.process_settings

formatters:
    simple:
        class: logging.Formatter
        format: "%(asctime)s - %(name)s - %(levelname)s - %(funcName)s \n %(message)s \n"

